version: "3"

volumes:
  postgres-data:
networks:
  payments:

services:
  db:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
      - POSTGRES_DB=payments
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .:/app
    networks:
      - payments
    ports:
      - 5432:5432
